export const ADD_CHILD_BLOCK = 'ADD_CHILD_BLOCK';
export const ADD_ELEMENT = 'ADD_ELEMENT';
export const CHANGE_ELEMENT_TYPE = 'CHANGE_ELEMENT_TYPE';
export const SAVE_ELEMENT_CONTENT = 'SAVE_ELEMENT_CONTENT';
export const SAVE_QUILL_INNERHTML = 'SAVE_QUILL_INNERHTML';
export const DELETE_BLOCK = 'DELETE_BLOCK';

export const LOAD_STORE = 'LOAD_STORE';

export const TOGGLE_EDIT_LAYOUT = 'TOGGLE_EDIT_LAYOUT';
export const TOGGLE_EDIT_TEXT = 'TOGGLE_EDIT_TEXT';
export const FOCUS_BLOCK = 'FOCUS_BLOCK';
export const TOGGLE_TOOLBAR = 'TOGGLE_TOOLBAR';

export const UPDATE_IMAGE_SRC = 'UPDATE_IMAGE_SRC';

export const SET_STORE_SAVED = 'SET_STORE_SAVED';

export const SAVE_MENU = 'SAVE_MENU';

export const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE';
export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';

export const SET_DATA_SOURCES = 'SET_DATA_SOURCES';

export const TOGGLE_PUBLISH_PAGE = 'TOGGLE_PUBLISH_PAGE';
